In [34]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score, mean_absolute_error

In [20]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

In [22]:
df = pd.read_csv('data/laptop_df.csv')

In [30]:
df.head(1)

,Unnamed: 0,price,manufacturer,graphics_copressor,ram,processor_brand,touchable,ips,ppi,cpu_name,memory,os
0,0,2287.0,Microsoft,NVIDIA,8,Intel,1,0,267.077872,Intel Core i7,256,Windows

In [31]:
df.drop(columns=['Unnamed: 0'], inplace=True)

In [32]:
df.head(1)

,price,manufacturer,graphics_copressor,ram,processor_brand,touchable,ips,ppi,cpu_name,memory,os
0,2287.0,Microsoft,NVIDIA,8,Intel,1,0,267.077872,Intel Core i7,256,Windows

In [23]:
X = df.drop(columns=['price'])
y = np.log(df['price'])

In [24]:
X

,Unnamed: 0,manufacturer,graphics_copressor,ram,processor_brand,touchable,ips,ppi,cpu_name,memory,os
0,0,Microsoft,NVIDIA,8,Intel,1,0,267.077872,Intel Core i7,256,Windows
1,1,Microsoft,NVIDIA,16,Intel,1,0,240.370085,Intel Core i7,256,Windows
2,2,Dell,NVIDIA,64,Intel,0,0,141.211998,Intel Core i9,2048,Windows
3,3,Dell,NVIDIA,8,Intel,0,0,141.509717,Intel Core i7,1024,Windows
4,4,Microsoft,NVIDIA,16,Intel,0,0,240.370085,Intel Core i7,1024,Windows
...,...,...,...,...,...,...,...,...,...,...,...
1100,1257,Lenovo,AMD,16,AMD,1,1,157.350512,AMD Ryzen 7,1024,Windows
1101,1258,Lenovo,Intel,20,Intel,0,0,141.211998,Other Intel Processor,1024,Windows
1102,1259,Lenovo,NVIDIA,32,Intel,0,0,188.679623,Intel Core i9,1024,Windows
1103,1260,Lenovo,NVIDIA,32,Intel,1,1,157.350512,Intel Core i7,1024,Windows
1104,1261,Lenovo,NVIDIA,32,Intel,0,1,157.350512,Intel Core i7,1024,Windows

In [25]:
X.drop(columns=['Unnamed: 0'], inplace=True)

In [26]:
X

,manufacturer,graphics_copressor,ram,processor_brand,touchable,ips,ppi,cpu_name,memory,os
0,Microsoft,NVIDIA,8,Intel,1,0,267.077872,Intel Core i7,256,Windows
1,Microsoft,NVIDIA,16,Intel,1,0,240.370085,Intel Core i7,256,Windows
2,Dell,NVIDIA,64,Intel,0,0,141.211998,Intel Core i9,2048,Windows
3,Dell,NVIDIA,8,Intel,0,0,141.509717,Intel Core i7,1024,Windows
4,Microsoft,NVIDIA,16,Intel,0,0,240.370085,Intel Core i7,1024,Windows
...,...,...,...,...,...,...,...,...,...,...
1100,Lenovo,AMD,16,AMD,1,1,157.350512,AMD Ryzen 7,1024,Windows
1101,Lenovo,Intel,20,Intel,0,0,141.211998,Other Intel Processor,1024,Windows
1102,Lenovo,NVIDIA,32,Intel,0,0,188.679623,Intel Core i9,1024,Windows
1103,Lenovo,NVIDIA,32,Intel,1,1,157.350512,Intel Core i7,1024,Windows
1104,Lenovo,NVIDIA,32,Intel,0,1,157.350512,Intel Core i7,1024,Windows

In [27]:
y

0       7.734996
1       8.006034
2       8.004700
3       7.600402
4       8.006034
          ...
1100    7.207119
1101    6.378426
1102    8.582981
1103    7.521859
1104    7.414573
Name: price, Length: 1105, dtype: float64

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2)

## Linear Regression

In [40]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf', OneHotEncoder(sparse=False, drop='first'), [0,1,3,7,9])
], remainder='passthrough')

step2 = LinearRegression()

pipe = Pipeline([
    ('step1', step1),
    ('step2', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

print('R2 score ',r2_score(y_test, y_pred))
print('MAE ', mean_absolute_error(y_test, y_pred))

R2 score  0.8575468283787182
MAE  0.19262674803608282

In [41]:
np.exp(0.19)

1.2092495976572515

## Ridge

In [42]:
step1 = ColumnTransformer(transformers=[
    ('col_tnf', OneHotEncoder(sparse=False, drop='first'), [0,1,3,7,9])
], remainder='passthrough')

step2 = Ridge(alpha=10)

pipe = Pipeline([
    ('step1', step1),
    ('step2', step2)
])

pipe.fit(X_train, y_train)

y_pred = pipe.predict(X_test)

print('R2 score ',r2_score(y_test, y_pred))
print('MAE ', mean_absolute_error(y_test, y_pred))

R2 score  0.8520749158084466
MAE  0.1956002645708391